
spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: eureka-server
server:
  port: 2001
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
spring:
  profiles: test
  application:
    name: eureka-server
server:
  port: 2002
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/