spring:
  profiles:
    active:
    - dev
---
server:
  port: 5002
spring:
  profiles: dev
  application:
    name: spring-cloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:2001/eureka/

---
server:
  port: 5003
spring:
  profiles: test
  application:
    name: spring-cloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:2001/eureka/

