spring:
  profiles:
    active:
    - dev
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  profiles: dev
  application:
    name: consul-server-dev
  cloud:
    consul:
      host: localhost
      port: 8500
server:
  port: 3001
mybatis:
  mapper-locations: classpath*:com/polymerization/module/**/mapper/*Mapper.xml
  type-aliases-package: com.polymerization.module.*.mapper
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  profiles: test
  application:
    name: consul-server-test
  cloud:
    consul:
      host: localhost
      port: 8500
server:
  port: 3002
mybatis:
  mapper-locations: classpath*:com/polymerization/module/**/mapper/*Mapper.xml
  type-aliases-package: com.polymerization.module.*.mapper