spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: consul-server-dev
  cloud:
    consul:
      host: localhost
      port: 8500
server:
  port: 3001
---
spring:
  profiles: test
  application:
    name: consul-server-test
  cloud:
    consul:
      host: localhost
      port: 8500
server:
  port: 3002